//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServPaci
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class paciente
    {
        public tipo_docume tipo_docume { get; set; }
        public string tipo_documento { get; set; }
        public int numero_documento { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public int telefono { get; set; }
        public DateTime fecha_nacimiento { get; set; }
        public string estado_afiliacion { get; set; }
        public tipo_estado tipo_estado { get; set; }
    }
    public enum tipo_docume
    {
        CC_Cedula, TI_Tarjeta_de_Identidad, PA_Pasaporte
    }
    public enum tipo_estado
    {
        Activo, Inactivo
    }
}
